### ISSUE TITLE
How to change language?

### ISSUE THREAD

**Issue by veganexe** [meetDeveloper/googleDictionaryAPI#1]
Suppose I want to use Spanish, how do I set it as default?

**Comment by meetDeveloper** [comment]
IBM Cloud [toolchain](https://console.ng.bluemix.net/devops/toolchains/623ac46c-aeaa-4433-a262-223430c2e0af?env_id=ibm%3Ayp%3Aus-south "googleDictionaryAPI"): [Delivery Pipeline](https://console.ng.bluemix.net/devops/pipelines/43a8bfc9-4989-4464-8299-979f59631a9c?env_id=ibm%3Ayp%3Aus-south "googleDictionaryAPI") deployed [googleDictionaryAPI](https://github.com/meetDeveloper/googleDictionaryAPI/releases/tag/deploy-ibm-yp-eu-gb-lifeplusplus-API-s-20180731-041607 "deploy-ibm-yp-eu-gb-lifeplusplus-API-s-20180731-041607") to [API's](https://console.bluemix.net/apps/0971aef0-04d8-454a-b263-f77d06d21309?env_id=ibm:yp:eu-gb "ibm:yp:eu-gb:lifeplusplus:API's"), including commit 4d8aeb345e63424525be68992ae94f1aa7cafe64

**Comment by meetDeveloper** [comment]
I implemented this feature, sorry for the delay. Kindly provide your feedback. @veganexe

**Comment by meetDeveloper** [comment]
Implemented.
