### ISSUE TITLE
Your Review for new Website

### ISSUE THREAD

**Issue by meetDeveloper** [meetDeveloper/googleDictionaryAPI#11]
I have changed website for the API, and I need your feedback on how it is. Kindly tell me if you want any changes or addition. Your feedback is appreciated.

**Comment by GE0NE** [comment]
How do I get the JSON payload now? 
Before it used to return nothing but the JSON which is why I loved it; I didn't have to filter through anything. Now I can't seem to find the data in JSON format at all, and I have to use BeautifulSoup to get the data I need from the HTML.

**Comment by meetDeveloper** [comment]
@GE0NE  I was just testing, you will get the data from JSON. I was testing as API was not working, I figured it out google put recaptcha challenge due to too many request too google to get the meaning. I will soon purchase many IP's so that API continue running without any interrupt.

**Comment by martin-martin** [comment]
Hi! I added some changes to the website design here as a [PR](https://github.com/meetDeveloper/googleDictionaryAPI/pull/15). Check it out and let me know if you like it @meetDeveloper  :)
Tried to keep it simple, but still add some example responses and the necessary info all on one page.

**Comment by meetDeveloper** [comment]
@martin-martin Thanks for all your work, also the API is now taking from google and as well as oxford, if you have some feature to suggest, I will be more than happy to implement it. Closing this issue, moving feature request out of issues.
