### ISSUE TITLE
Multiple Languages Added

### ISSUE THREAD

**Issue by meetDeveloper** [meetDeveloper/googleDictionaryAPI#12]
I have added more languages in dictionary API. 

 Kindly provide your feedback if the feature is working correct. 

What it does is if you send extra parameter **lang='language code'** along with **define**, then the word is searched in that language dictionary, example if you send request  **/?define=bonjour&lang=fr**, where **fr** is language code for french. The result will be meaning of **bonjour** in french. The word have to be present in that language, i.e if you send **/?define=hello&lang=fr**, it will not give you french meaning as **hello** is not present in french language.

List of languages supported can be found <a href="https://googledictionaryapi.eu-gb.mybluemix.net/languageCode.txt">here</a> for your reference.

**Comment by djmbritt** [comment]
I've been experiencing some issues with other languages. 
When I query certain words in spanish or french it returms 404 for some words.
The french example is not working properly for example.

**Comment by meetDeveloper** [comment]
Multiple languages had issues, I have fixed it now, kindly check and let me
know.

**Comment by djmbritt** [comment]
Yes, it's working properly. 
Thank you!
