### ISSUE TITLE
Due to High Traffic - API gets detected by google

### ISSUE THREAD

**Issue by meetDeveloper** [meetDeveloper/googleDictionaryAPI#13]
Due to high amount of traffic, now the request I send to google server side does not go through and instead, it shows recaptcha page, and so all of you people must be experiencing downtime. I am finding solution for the problem, Sorry for inconvenience caused.

**Comment by ojoven** [comment]
Hey @meetDeveloper, now it seems to be working.
Wanted to ask you, what's the rate limit for the calls?
Do you have any info on that? What was that high amount of traffic?

Thanks for your work.

**Comment by meetDeveloper** [comment]
@ojoven I actually query google at the back-end and then scrap the results, so google limits the call.  I am getting 6-7 request per minute. and google rate limit is around 10  per hour, they eventually detect that an application is scrapping their results.

**Comment by meetDeveloper** [comment]
@ojoven   I have changed the API a little kindly see the latest post.

**Comment by kovinet** [comment]
Hey
I need word definitions for larger amount, so I wanted to host app myself, but at current source code all request go to ```var url = 'https://en.oxforddictionaries.com/search?filter=noad&query=' + req.query.define;``` and there is no language support at all (I need Turkish)...
I guess you have different code deployed on https://googledictionaryapi.eu-gb.mybluemix.net as the one in master branch currently?
If I use your API endpoint I guess it will get blocked after certain amount of requests?

**Comment by meetDeveloper** [comment]
@kovinet I will give you the deployed code.

**Comment by kovinet** [comment]
@meetDeveloper thank you!

**Comment by kovinet** [comment]
@meetDeveloper when could you share deployed code? I would like to contribute with improvements to make Turkish language support better... Thanks.

**Comment by meetDeveloper** [comment]
@kovinet Will give you deployed code, after I add support for multiple definition for languages other than english and better json structure, I will then update github to reflect new code, closing this issue, will move feature request out of issues.
