### ISSUE TITLE
German to English possbile？

### ISSUE THREAD

**Issue by yucongo** [meetDeveloper/googleDictionaryAPI#17]
Is it possible to lookup a word in one language and get the explanation in another language? For example, look up a German word machen,  and get the meaning in English?

Thank a lot.

**Comment by meetDeveloper** [comment]
@yucongo  I will see to it, currently it is not available, I will implement it soon. May I ask you what are you designing such that you need such functionality.

**Comment by meetDeveloper** [comment]
It will help me understanding your need and better designing the solution.

**Comment by meetDeveloper** [comment]
@yucongo I have changed the API a little kindly see the latest post.

**Comment by meetDeveloper** [comment]
Closing this issue, as this won't be supported in near future.
