### ISSUE TITLE
Usage rights

### ISSUE THREAD

**Issue by MatteoAvalle** [meetDeveloper/googleDictionaryAPI#18]
Hi,
I really like your API and I'm considering introducing it in one of my websites as "free feature", even if inside a commercial website, with paying customers. I was wondering if you have any insights about what are the usage limits of the data your API fetches: do I risk anything in showing API results in my website? (I would obviously cache results so that the volume of searches would be negligible)
Thank you

**Comment by meetDeveloper** [comment]
Actually I  am using results from Oxford Dictionary, from which google sources the result, and currently I am only scrapping the result, I have only recently changed the source from directly taking from google to Oxford from which google takes, so I do not know the current limits. As far as I know it would be harmless, and you can go on putting that.

Also I am soon planning to make the API limitless by also making users get their API key for free from Oxford Dictionary, and sending that to me, and in the backend I will use the key to send request to Oxford, and then display the data to the end user, this way the usage limit would depend on that person.

As each will have its own key, they are not limited by how other people uses this API. 

Does that answer your query?

**Comment by martin-martin** [comment]
Hei @meetDeveloper - so that means you are not going across Google requests anymore?

**Comment by meetDeveloper** [comment]
@martin-martin I am not directly using their API, rather I am scrapping their results, their API has limitations, also about the problem, Yes I have implemented the workaround for that issue, and one can use API client side also.

Oxford Dictionary API provides many details that are too much for a person who is implementing an personal project, my API provides the data in much simpler way so that it is easier to use.

**Comment by martin-martin** [comment]
Sure, that makes sense. However I would suggest to then change the name to
reflect that it's now about the Oxford dict API.
I've heard that Google uses _partly_ Oxford's API, but I think they have
other sources and data as well.

**Comment by meetDeveloper** [comment]
@martin-martin They actually use the oxford dictionary data for english language. Actually I am thinking to change the name to unofficial Google Dictionary API, is that ok??

**Comment by MatteoAvalle** [comment]
Watch out! Oxford APIs are indeed free under a certain call volume, but you have to contact them directly and explicitly get an authorization, if you cache the results (which is more or less what you are doing right now I guess). 

Anyway, yes that DID answer my query, thank you very much :) Differently from google, Oxford has clear licensing terms I can give to my legal guys to make them feel safer... :D

**Comment by meetDeveloper** [comment]
@MatteoAvalle So are you going to use this API in your website?? And should I go with the give me the api key and I will send it to Oxford method to increase call volumes??

**Comment by MatteoAvalle** [comment]
I'm not sure, I'm sorry :( I will have to discuss it with my team, but we were unsure whether to use your solution OR Oxford APIs, directly... so knowing that the source is the same might lead us more towards going directly there, but I'll let you know :) integrating your API is still faster, so there are still reasons to use yours.

**Comment by meetDeveloper** [comment]
@MatteoAvalle You can take Key from them and pass it to my api, that way I could use that and get data and present it in the way I present it now, it would be easier to integrate that way. If you want that?

**Comment by meetDeveloper** [comment]
@martin-martin There?? Actually everything was same, as google takes from oxford for english language, I compared all results and they are exactly same, so that is why I did not changed the name, as they only use oxford API, only thing is instead of taking from them, I am taking from where they take from, am i thinking right??

**Comment by martin-martin** [comment]
I understand. There's more information that Google provides (word usage,
etymology etc.) But you weren't pulling that data before.
I don't know, to me it feels better to name it Oxford Dictionary API, but I
understand it will be more attractive and easier to find if called Google
Dictionary API.

**Comment by meetDeveloper** [comment]
@martin-martin Actually Oxford also provides all those information exactly what all google provides, I was not taking it before, so I left it now in this version also, as I wanted to make an simple API for users, although I have included multiple definitions and I will enable it by another parameter 'multidefintion=true' . To not break all the app that are currently using this version.

**Comment by meetDeveloper** [comment]
@martin-martin https://en.wikipedia.org/wiki/Google_Dictionary#Languages

**Comment by martin-martin** [comment]
Yeah I mean sounds legit. You do what you think is best!
.
