### ISSUE TITLE
Dictionary Won't Work for other languages for some time

### ISSUE THREAD

**Issue by meetDeveloper** [meetDeveloper/googleDictionaryAPI#19]
Due to having change the structure of the program and various significant parameters.
Dictionary API won't work for languages other than English for sometime.
I will soon patch the issue and get it working.
Thanks for your support.

**Comment by abhagsain** [comment]
404 Not Found: Requested route ('googledictionaryapi.eu-gb.mybluemix.net') does not exist.
Is being shown even for English words.
BTW.  Thank you so much for this. ^_^

**Comment by abhagsain** [comment]
404 Not Found: Requested route ('googledictionaryapi.eu-gb.mybluemix.net') does not exist.
Is being shown even for English words.
BTW. Thank you so much for this API. ^_^

**Comment by meetDeveloper** [comment]
@abhagsain Sorry, it is running now, it got into some problem. Also is there feature you wish to see??

**Comment by abhagsain** [comment]
@meetDeveloper Yes. It's working now. Thanks.
If you can limit the number of synonyms for a given word, 3-4 are sufficient. I think!? Of course, someone can fetch more if they want to! I felt the need for this feature yesterday :P
If it's easy. Please add it ^_^

**Comment by meetDeveloper** [comment]
@abhagsain API is crashing sometime, as it is facing some issue, I am correcting that issue, and service will be restored shortly.

**Comment by sergiuiacob1** [comment]
Hello. The api currently works only for English. Any ETA on when it could be available for other languages as well? Thanks!

**Comment by meetDeveloper** [comment]
Which language do you want to have?

**Comment by sergiuiacob1** [comment]
> Which language do you want to have?
> […](#)

Well, I'm currently developing a multi-lingual dictionary, so... all of them, haha :D. A week or two ago I tested your API and it had multiple languages, like French, Spanish, Italian, German and so on. I also need Romanian, but I'll use a different API for that one.

**Comment by meetDeveloper** [comment]
@abhagsain @sergiuiacob1  I have changed the API a little kindly see the latest post.

**Comment by meetDeveloper** [comment]
@abhagsain Do y

**Comment by meetDeveloper** [comment]
Have you checked now?

**Comment by meetDeveloper** [comment]
Issue resolved, no change needed for synonym work, have to show all synonyms at once.
