### ISSUE TITLE
An searchbar in the welcome page

### ISSUE THREAD

**Issue by veganexe** [meetDeveloper/googleDictionaryAPI#2]
I would understand if you would prefer it to be a minimalistic API, but an optional welcome page with a search bar would help alot for UX. I would delete the Google dictionary add-on and bookmark if it were the case :D

**Comment by meetDeveloper** [comment]
I would implement that  today itself, thanks for suggestion, it is very fulfilling to see the thing you developed used by others. Thanks.

**Comment by meetDeveloper** [comment]
Added search bar. Thanks for the suggestion. You can request for any feature and I will try to implement it.

**Comment by meetDeveloper** [comment]
@veganexe  Hello??

**Comment by meetDeveloper** [comment]
@veganexe  hi

**Comment by meetDeveloper** [comment]
Implemented
