### ISSUE TITLE
CORS

### ISSUE THREAD

**Issue by StanNL** [meetDeveloper/googleDictionaryAPI#24]
The website does not support cross-origin resource sharing (CORS). I'm not an expert in terms of back-end web development, but I feel like this should be easy to fix server-sided, right? Whenever I send an API request via AJAX in Javascript, I get the following error:
![image](https://user-images.githubusercontent.com/43415012/49606641-32597680-f994-11e8-8eef-09b978b164a9.png)

I must say though that I really like the API you created and its simplicity, albeit a little slow due to the high latency. Keep up the good work!

**Comment by meetDeveloper** [comment]
@StanNL Thanks, It is because of people like you I enjoy my work on this API. 
Regarding problem, I did support CORS long back itself, I will check why did it replied like this, but website support CORS long back.

**Comment by meetDeveloper** [comment]
I checked it and it seems to be working for me, Can you step wise tell what did you do??

**Comment by StanvBaarsen** [comment]
-- deleted --

**Comment by meetDeveloper** [comment]
@StanNL No Problem, If you want me to add any new features in dictionary. Feel free to tell me. May I ask how are you using this API?

**Comment by StanvBaarsen** [comment]
-- deleted --

**Comment by meetDeveloper** [comment]
@StanNL I have to click search and then it leads me to oxford page. It isn't showing meaning there itself.

**Comment by StanvBaarsen** [comment]
-- deleted --

**Comment by StanvBaarsen** [comment]
-- deleted --

**Comment by StanvBaarsen** [comment]
-- deleted --

**Comment by StanvBaarsen** [comment]
-- deleted --
