### ISSUE TITLE
Multiple definition support for languages other than english.

### ISSUE THREAD

**Issue by meetDeveloper** [meetDeveloper/googleDictionaryAPI#25]
I have finally added multiple definitions feature. If you google suppose _define set_, it will give you many definitions, I till now only used the first definition it provided, but now instead of first I show every definition. Thanks to @ScottEnock for suggesting the feature  #5 and @martin-martin  and @roaugusto for giving me motivation to do it finally #23 . I apologise for implementing it so late. It is a very useful feature, life caught me and I was not able to commit whole time to implement it.

Coming to developers who uses this API, you only have to change single line of code, and and I am giving array now, which contains multiple sets of definitions, earlier I was giving only the first set of definition, so if you want first set you only have to select first object from the array, and nothing else would be changed.  

I am attaching the images to tell what I mean by multiple sets of definitions.

Thank you for your continuous support.

![capture](https://user-images.githubusercontent.com/32453612/49641578-92a0f480-fa36-11e8-9b94-6175a62e807c.PNG)
![capture2](https://user-images.githubusercontent.com/32453612/49641586-97fe3f00-fa36-11e8-97cc-60c90385b2dc.PNG)

**Comment by kovinet** [comment]
I have tested multiple definitions for Turkish language and they don't seem to work.

For example word 'ay', on Google the result is following:

![image](https://user-images.githubusercontent.com/707846/54433776-b5c9f700-473d-11e9-8174-0356129162f1.png)


but API returns only the first definition:


```
{
    "word": "ay",
    "meaning": {
        "

": [
            {
                "definition": "birdenbire duyumsanan ağrı ya da acıyı anlatır.",
                "example": "Ay, ölüyorum!"
            },
            {
                "definition": "türlü coşkusal duyguları anlatır.",
                "example": "Ay, ne güzel bir çocuk!"
            }
        ]
    }
}
```

Are multiple definitions supported only for English?

**Comment by meetDeveloper** [comment]
@kovinet You got it right, I have implemented that for english only currently, will update for other languages soon.

**Comment by TheMode** [comment]
Waiting for multi-language support :)

**Comment by meetDeveloper** [comment]
@TheMode Life is getting me, some work load, will surely get this done in upcoming weekend.

**Comment by meetDeveloper** [comment]
@kovinet @TheMode Have implemented it, can you see if that is what you wanted?
