### ISSUE TITLE
502 Bad Gateway

### ISSUE THREAD

**Issue by deepsworld** [meetDeveloper/googleDictionaryAPI#26]
The API is down right now. Can you please fix it, we need it for our school project.

**Comment by meetDeveloper** [comment]
@deepsworld I will correct it very shortly. Meanwhile you can use https://mydictionaryapi.appspot.com/. Tell me if this works for you. Sorry for the inconvenience.

**Comment by deepsworld** [comment]
It works, thank you much.

**Comment by meetDeveloper** [comment]
@deepsworld Original Site is up and working. Thanks for your patience, May I ask how were you using the API for your school project.

**Comment by deepsworld** [comment]
We making an Android dictionary app.

**Comment by meetDeveloper** [comment]
@deepsworld Do you need anymore feature in the API?

**Comment by deepsworld** [comment]
We just needed an easy to use API. But thank you for your help and work.
