### ISSUE TITLE
Can you all list features that you all want to have in this api?

### ISSUE THREAD

**Issue by meetDeveloper** [meetDeveloper/googleDictionaryAPI#29]
If you wish to have some feature in API, can you please this them all here. Then it would be easy for me to track them. I will implement them as soon as I can.

Also if you would like to contribute to the API it would be very beneficial for us all.

**Comment by alextenev** [comment]
Hi!

Thanks for the API.

Could you please add the audio file links? The ones that pronounce the word.

e.g https://ssl.gstatic.com/dictionary/static/sounds/20180430/hello--_gb_1.mp3

**Comment by meetDeveloper** [comment]
@alextenev Ok will do so.

**Comment by meetDeveloper** [comment]
@alextenev I have added the feature, sorry for delay.

**Comment by meetDeveloper** [comment]
@alextenev Can you confirm it is what you asked for?

**Comment by meetDeveloper** [comment]
@alextenev Sorry for the delay in response, I have added the feature you request a month back, waiting for your reply.
