### ISSUE TITLE
Looking for the word pronunciation

### ISSUE THREAD

**Issue by rawandahmad698** [meetDeveloper/googleDictionaryAPI#3]
This is not an issue, it works great.. just a tip

I'd be more happy to see the word pronunciation included in this awesome script, e.g: Love: /lʌv/
And +1 if you could order the data as an array

**Comment by meetDeveloper** [comment]
I have implemented this, could you check it and tell me is this what you were looking for??

**Comment by rawandahmad698** [comment]
Thanks, Perfect 👌🏻

**Comment by meetDeveloper** [comment]
@rawandahmad698 I also made an extension https://addons.mozilla.org/en-US/firefox/addon/dictionary-anyvhere/?src=search, feel free to check it out, if it helps you.
