### ISSUE TITLE
I have fixed multiple languages issue, sorry for the long delay. (working only for https://googledictionaryapi.eu-gb.mybluemix.net/)

### ISSUE THREAD

**Issue by meetDeveloper** [meetDeveloper/googleDictionaryAPI#30]
I have fixed multiple languages, and it is working again. Though for time being multiple definitions will cease to work, I will add them again in weekend.

If you were using that, kindly use the other URL https://mydictionaryapi.appspot.com/.  I will fix the issue for https://googledictionaryapi.eu-gb.mybluemix.net/, in weekend and then there will be consistency across all.

**Comment by krv5vignesh** [comment]
Will https://mydictionaryapi.appspot.com/ work continuously or should we change it back in the future?

**Comment by meetDeveloper** [comment]
It will work continuosly...

**Comment by MuVen** [comment]
Have you changed JSON response ? 

Earlier I requested for JSONArray it use to work, the same code fails now. 

And you can also see difference in the response given by two API'S given by you. Can you make it as earlier and streamline these two APIs for better consistency

**Comment by meetDeveloper** [comment]
@MuVen I am making it more consistent  now, Sorry for the inconvenience.

**Comment by MuVen** [comment]
When can we expect a fix for this ?

**Comment by meetDeveloper** [comment]
@MuVen Today.

**Comment by MuVen** [comment]
Is there any plan to change the existing API/Response in future ? Because based on this API im planning to build an application.

**Comment by meetDeveloper** [comment]
@MuVen Expect it to be same as earlier, you will only use english?

**Comment by MuVen** [comment]
for now im using english, planing to scale for other languages as well

**Comment by meetDeveloper** [comment]
@MuVen Oh, expect the english one to be same, I am fixing it today itself, for other I will fix in 2-3 days.

**Comment by MuVen** [comment]
Okay !!!

**Comment by meetDeveloper** [comment]
@MuVen 👍

**Comment by meetDeveloper** [comment]
@MuVen I have fixed kindly see.

**Comment by meetDeveloper** [comment]
@krv5vignesh You can shift to  https://googledictionaryapi.eu-gb.mybluemix.net/, I have now made both endpoint consistent, when you search for english words,

**Comment by MuVen** [comment]
Working !!!

**Comment by meetDeveloper** [comment]
@MuVen Is everything working correctly now?
