### ISSUE TITLE
API failing with non English characters

### ISSUE THREAD

**Issue by kovinet** [meetDeveloper/googleDictionaryAPI#31]
For Turkish language, a request for a word which has one of the non standard characters, such as: Ş, Ç, I, Ü, Ğ, Ö returns an error.

For example the word "kuş": request to /?define=kuş&lang=tr returns 404 error, but Google search for "kus nedir" produces normal results. Same for other word for Turkish with characters not present in English alphabet.

**Comment by kovinet** [comment]
Hi. I am also noticing unpredictable results for some words, for example "abla" for Turkish language. 

Requesting like this (there is no special chars in this word):
https://googledictionaryapi.eu-gb.mybluemix.net/?define=abla&lang=tr

in most cases I get 404 response, but in some cases it works correctly (JSON definition). It's like 90% of times it doesn't work but 10% of tries for same word it works, strange ...

**Comment by meetDeveloper** [comment]
@kovinet I am looking into it, most probably, when you search on google 'define abla' or 'define kuş', it sometime gives and sometimes do not give result, maybe I have to change define to nedir. I will fix it today, sorry for late reply, life caught me in other works.

**Comment by kovinet** [comment]
@meetDeveloper yes, for Turkish you should replace 'define' with 'nedir' for Google query, which means define in Turskih. In this way results are more predictable. I would fix it myself and create a Pull Request but the code in repo is not the latest as I see...

**Comment by kovinet** [comment]
@meetDeveloper did you maybe manage to fix it for Turkish language by  replacing define with 'nedir'?
As mentioned before, I have looked into source code but there it looks like you are fetching results from Oxford dictionary (not from Google), so I guess you have different code deployed on server for other languages? Could you share that code also?

**Comment by meetDeveloper** [comment]
@kovinet Sorry for the delay, I got stuck in life, I have fixed the bug.

**Comment by meetDeveloper** [comment]
What was happening with `kuş` was the `ş` is special character, and when url is encoded it gets some code like `%C5%9F`, now I did not allowed any special character earlier, by returning if `%` is detected after encoding url, I wanted this check for not allowing spaces between words, as google as far as I know does not support them anyway, and hitting google for words that have spaces between them, would just rate limit me, so I had this check, now I just made the check to check for `%20`, as `%20` mean space character, so now all special character works, and check is still in place for space character.

**Comment by meetDeveloper** [comment]
@kovinet Is it ok?

**Comment by kovinet** [comment]
@meetDeveloper yes, I have tested with couple of Turkish words and it is working now!

**Comment by kovinet** [comment]
Hi again. There is one more issue I have regarding spaces in words. There are some words in Turskih which are only meaningful in pair like 'abur cubur', etc. There are thousands of words like this, and if you google for "abur cubur nedir" it gives you definition like it was a single word. But your API ignores words with spaces as you have implemented. Could you make an exception and allow 1 space? 
I am currently using your API and this is one thing that is missing / not working as desired ...

**Comment by meetDeveloper** [comment]
@kovinet Is this issue resolved?

**Comment by meetDeveloper** [comment]
@kovinet Sorry for the extreme delay, it slipped out of my mind.

**Comment by meetDeveloper** [comment]
@kovinet So no turkish word can have more than one space?

**Comment by kovinet** [comment]
I think there are some examples where 3 words for a "word", so there are 2
spaces, but this can be ignored. There are quite a lot with one space
though... For example "afiyet olsun", etc.

**Comment by meetDeveloper** [comment]
@kovinet I removed all together space check for turkish word, google will anyway return no meaning if word is wrong, and most people use API for english for which the check is still present.

**Comment by meetDeveloper** [comment]
@kovinet Can you confirm if it is working for your need?

**Comment by meetDeveloper** [comment]
@kovinet Can you confirm?

**Comment by kovinet** [comment]
It is working fine now.  Thank you @meetDeveloper
