### ISSUE TITLE
Support for Chinese

### ISSUE THREAD

**Issue by ghlai9665** [meetDeveloper/googleDictionaryAPI#33]
Queries for Chinese words don't seem to be working. Definitions not found.

**Comment by meetDeveloper** [comment]
@ghlai9665 Can you send me words for which it is not working?

**Comment by CR-97** [comment]
The API Link :https://googledictionaryapi.eu-gb.mybluemix.net/?define=bird&lang=zh-CN
![image](https://user-images.githubusercontent.com/30256135/59753573-feea9380-92b6-11e9-8899-553cdc83f8be.png)

I also facing this issue, when i search run for Chinese language. It return me the meaning in English not in Chinese

**Comment by meetDeveloper** [comment]
@CR-97 @ghlai9665 It depend on google, as I am using their result, my experiment shows that for it to show meaning in chinese the word should be in chinese as well, kindly search for a chinese word, and tell if that is working.
