### ISSUE TITLE
Language of origion

### ISSUE THREAD

**Issue by rrbadam** [meetDeveloper/googleDictionaryAPI#34]
Hi Suraj Jain,

I love the api provided by you to learn about words. Can this api be extended to provide etymology (languageOfOrigin).

You can either show full graph in transformed text if possible. If not possible, just the text also would be fine ("early 17th century: from French, from Provençal acolada, literally ‘embrace around the neck (when bestowing knighthood)’, from Latin ad- ‘at, to’ + collum ‘neck’.").

Thanks,
Rajesh

Thanks,
![unnamed](https://user-images.githubusercontent.com/8441351/57423840-3a635e00-7233-11e9-8fd8-982048272964.png)

Rajesh

**Comment by meetDeveloper** [comment]
@rrbadam I have just implemented it, can you confirm. I have added the just the text, full graph in transformed text will make the query too slow. And make it unnecessary complicated, all the important information is available in the text.

**Comment by meetDeveloper** [comment]
@rrbadam Sorry for the delay, life caught me, also I have checked the words you told were having different DOM structure.
