### ISSUE TITLE
https://mydictionaryapi.appspot.com link is not working

### ISSUE THREAD

**Issue by krv5vignesh** [meetDeveloper/googleDictionaryAPI#37]
https://mydictionaryapi.appspot.com - This link is not working and does not return definition for any of the words. The https://googledictionaryapi.eu-gb.mybluemix.net link works though.

**Comment by hrai** [comment]
I think the codebase is not up-to-date.

https://github.com/meetDeveloper/googleDictionaryAPI/issues/36#issuecomment-503070779

**Comment by meetDeveloper** [comment]
Yes code-base is not up to date, do you need that endpoint? I will update it once I make sure the structure is what I want it to have, this weekend will take up the issues and finish refactoring the code.

You guys can list all features that you want, and will make a separate issue for each feature, it helps to track it,

**Comment by meetDeveloper** [comment]
@krv5vignesh I was wondering I have seen this username somewhere, then I went to your profile, then I remembered the dictionary extension you made, nice work.

**Comment by meetDeveloper** [comment]
@krv5vignesh I also made one

**Comment by meetDeveloper** [comment]
@krv5vignesh I have fixed this can you check.
