### ISSUE TITLE
Please add a license so this project can be used in my project.

### ISSUE THREAD

**Issue by Niweera** [meetDeveloper/googleDictionaryAPI#39]
I am developing an application related words and their definitions. I need to use this API with few modifications in my project. Can you please add a license so that I can use it in my project? (I hope it will be an open source license.)

**Comment by meetDeveloper** [comment]
@Niweera done, may I ask what are you using this API for?

**Comment by Niweera** [comment]
I am developing a micro-services app for finding words when given letters. Find the repo @ https://github.com/Niweera/wordhunter

**Comment by meetDeveloper** [comment]
@meetDeveloper Can you kindly fork this api, and then modify it for your dictionary api.
