### ISSUE TITLE
Empty objects are returned when provided certain words.

### ISSUE THREAD

**Issue by Niweera** [meetDeveloper/googleDictionaryAPI#40]
For example 'Zinc'

```json
[
  {
    "word": "zinc",
    "phonetic": "/zɪŋk/",
    "origin": "Mid 17th century from German Zink, of unknown origin.",
    "meaning": {
      "noun": [
        {
          
        }
      ],
      "verb": [
        {
          "definition": "Coat (iron) with zinc or a zinc compound to prevent rust.",
          "example": "the street lamps are adorned with tiny zinced crowns"
        }
      ]
    }
  }
]
```

For example 'Women'

```json
[
  {
    "word": "women",
    "phonetic": "/ˈwɪmɪn/",
    "meaning": {
      
    }
  }
]
```

For example 'Men'

```json
[
  {
    "word": "men",
    "phonetic": "/mɛn/",
    "meaning": {
      
    }
  }
]
```

I reviewed your code and found out that there is an issue with the code in line 205 to 207 in `app.js`.

```
if (definition.length === 0) {
           definition = $(item).find(".crossReference").first().text();
}
```
I suggest you to check the `crossReference` class again in the `Lexico.com` site and refactor the code.

Best regards.

**Comment by StevenLi-DS** [comment]
I think their API was also designed to just accept headwords only.

https://developer.oxforddictionaries.com/documentation

>TIP: Entries ONLY works for dictionary headwords. You may need to use the Lemmas endpoint first to link an inflected form back to its headword (e.g., pixels --> pixel).

**Comment by meetDeveloper** [comment]
@StevenLi-DS I have a way around that, and use that to convert all words like pixels to pixel, so that is not the problem. I know what is happening, will push a fix soon.

**Comment by Niweera** [comment]
> @StevenLi-DS I have a way around that, and use that to convert all words like pixels to pixel, so that is not the problem. I know what is happening, will push a fix soon.

Marvelous. Actually this is where I am stuck at my project. I found a temporary solution for this. But I am eagerly waiting for your solution. Thanks in advance...

**Comment by StevenLi-DS** [comment]
@meetDeveloper that would be great, but will the API just return the meaning of "man" or including "the plural form of man" as well when passing "men"

**Comment by Niweera** [comment]
> @meetDeveloper that would be great, but will the API just return the meaning of "man" or including "the plural form of man" as well when passing "men"
> ![image](https://user-images.githubusercontent.com/33796896/62837512-4f8ac700-bc3e-11e9-8035-ca756dee8bef.png)

I think there is a possibility to follow the hyperlink such as in the following example.
`https://www.google.com/search?q=define+men`
then follow the link as;
`https://www.google.com/search?q=define+men#dobs=man`

**Comment by ssabbarw** [comment]
I'm now stuck at this, was anybody able to find a work around or a permanent solution?
Kindly reply.

**Comment by meetDeveloper** [comment]
@ssabbarw Will take a closer look at this today. Sorry for the delay.

**Comment by meetDeveloper** [comment]
@ssabbarw @StevenLi-DS @Niweera Fixed the problems, now meanings will be shown for the words that are not headwords and also added fix for the word such as `zinc`. They had different kind of problems have fixed them. Kindly check and close the issue if you seem satisfied.

I am really sorry for the long delays, life was too hectic. I am now giving time to this API and improving it. Thanks a lot to you guys for using this API. It feels good when someone uses your project and build something on top of that.

**Comment by Niweera** [comment]
@meetDeveloper Sorry, I actually forgot that I opened issue since it has been a long time now. I have developed my own dictionary API on top of your dictionary API. Thanks to your API I learned a great many things.

**Comment by ssabbarw** [comment]
Hi @meetDeveloper   thanks for amazing work. Seems to be working for me too.
