### ISSUE TITLE
Phonetic critical problem

### ISSUE THREAD

**Issue by Farhad098** [meetDeveloper/googleDictionaryAPI#43]
Hi
There is an issue with phonetic extraction, which I consider it as critical. The pronunciation of a word may differ in its many usages, but the API returns only one pronunciation for a word. For example word "use", it has two pronunciations: /ju:z/ as a verb and /ju:s/ as a noun, but the API returns only /ju:z/.
Thanks

**Comment by meetDeveloper** [comment]
@Farhad098 Will fix this this weekend.

**Comment by doubleh311** [comment]
Hi @meetDeveloper, thanks to your API for my app but
Do you have any update in this issue? Still the phonetic in result return string instead array.
And the current respelling format is a bit more difficult than IPA.
Secondly, I've found out problem in the result which returns the pronunciation of the verb form for "record" is not correct, expected /ri'cord/.
 Thanks

**Comment by meetDeveloper** [comment]
@doubleh311 Looking into this today.

**Comment by doubleh311** [comment]
@meetDeveloper thanks for your response.
btw, I think the issue of pronunciations is from the data source

**Comment by meetDeveloper** [comment]
@doubleh311 I am using US dictionary instead of UK. Using this https://www.lexico.com/en/definition/record.

There are two types of phonetics Respelling and IPA. Respelling is /ˈrekərd/ whereas IPA is /ˈrɛkərd/.

I am using IPA.

**Comment by meetDeveloper** [comment]
@Farhad098 Sorry for so late reply, as I said I am using US dictionary. In US dictionary [use](https://www.lexico.com/en/definition/use) has no pronunciations. That is why I am not returning that.

**Comment by meetDeveloper** [comment]
@Farhad098 you can reopen the ticket if you encounter some problems, I would be happy to fix those. 😊
