### ISSUE TITLE
Support for languages other than English stop

### ISSUE THREAD

**Issue by pdji1602003** [meetDeveloper/googleDictionaryAPI#44]
Good morning, sir!

First off, thank you for this amazing service! This API is so useful.
I am incorporating this service to my website; however, I am facing a problem where no JSONs are returned except for English words.
I have tested with multiple languages such as French, German and Chinese, **but so far this API only works when the searched word is in English**. **In other languages, it won't return any JSON results.**
Does this API currently not support languages other than English?
Could you try to look into it when you have some time?
Thank you very much!

Photo attached below shows the result when searched word was in German.

<img width="989" alt="notFoundPage" src="https://user-images.githubusercontent.com/44464766/66711138-c6684b80-edb8-11e9-8cb0-a11b5bfea0f6.png">

Best regards!

**Comment by meetDeveloper** [comment]
I am fixing this, this will be fixed by tomorrow.

**Comment by pdji1602003** [comment]
Got it! 
Thank you for informing me! I am looking forward to seeing this great API back in service again! 

Best regards,
Lin

**Comment by meetDeveloper** [comment]
@pdji1602003 Can you check it again?

**Comment by pdji1602003** [comment]
@meetDeveloper It works now! I've tested it with different languages other than English and each time it returned the desired JSON file! Thank you for your work!

**Comment by meetDeveloper** [comment]
@pdji1602003 You are welcome :)
