### ISSUE TITLE
No Data From Response

### ISSUE THREAD

**Issue by Oceaneyes123** [meetDeveloper/googleDictionaryAPI#45]
I use axios get method but I didn't saw any data from the JSON response. Please help

`axios.get('https://googledictionaryapi.eu-gb.mybluemix.net?define=apple')
				.then(function(response){
						console.log(response)
}`

**Comment by meetDeveloper** [comment]
I am fixing this.

**Comment by meetDeveloper** [comment]
Can you check it again?

**Comment by Oceaneyes123** [comment]
Thank you :)
