### ISSUE TITLE
Cannot get definitions for phrases

### ISSUE THREAD

**Issue by evelynluw** [meetDeveloper/googleDictionaryAPI#47]
When I use the api to query a phrase, e.g. et cetera, I can't get the definition. But Google Dictionary actually supports phrase lookup: 
`
![Screen Shot 2019-10-26 at 12 48 11 PM](https://user-images.githubusercontent.com/23702556/67625149-f10dc780-f7ee-11e9-9cb7-f79271bc95fb.png)

**Comment by nathanielxd** [comment]
Wrong: https://googledictionaryapi.eu-gb.mybluemix.net/?define=et+cetera&lang=en
Correct: https://googledictionaryapi.eu-gb.mybluemix.net/?define=et_cetera&lang=en

Use **_** instead of spaces or **+**

**Comment by evelynluw** [comment]
Thanks! That worked.
