### ISSUE TITLE
Stability issues?

### ISSUE THREAD

**Issue by sks316** [meetDeveloper/googleDictionaryAPI#48]
I'm adding a define command to my Discord bot, [Mewtwo](https://github.com/sks316/mewtwo-bot/), using this API. Unfortunately, after attempting to define a word, the API sometimes stops responding with JSON for some minutes and sends a 404 page instead. This isn't an issue with the bot itself, as this issue is confirmed by opening the page in a web browser. I can't push an unstable command to the stable version of the bot, so I was wondering if you could look into what may be causing this.

**Comment by meetDeveloper** [comment]
@sks316 can you tell me the word and the language?

**Comment by sks316** [comment]
It happens with pretty much any word, and the language is English.

**Comment by colinamurgatroyd** [comment]
Hi,
Is there any update on this? I use this in an app and have also noticed that I'm getting 404 responses about 60% of the time. The language is English and does not appear to be specific to any word. The 404 responses appear to be sporadic, so sometimes I get the JSON definition in the response coming back okay and at other times I get a 404 (for the same word). The problem can be reproduced using Postman and using a browser (I'm using Safari).

**Comment by meetDeveloper** [comment]
@colinamurgatroyd Let me check this in this weekend.

**Comment by meetDeveloper** [comment]
@colinamurgatroyd I fixed this, can you check.

**Comment by meetDeveloper** [comment]
@colinamurgatroyd I will soon be updating API with massive changes that will solve this and related issue completely.

**Comment by colinamurgatroyd** [comment]
Thanks for letting me know. And thanks for the reply you sent just before
Xmas - apologies for not acknowledging that at the time. Will the
changes be backward compatible?

**Comment by meetSuraj** [comment]
@colinamurgatroyd Will support earlier version also, but new version will have better structure for easy usage. You can look at this issue for more information  https://github.com/meetDeveloper/googleDictionaryAPI/issues/32

**Comment by meetDeveloper** [comment]
@colinamurgatroyd Will support earlier version also, but new version will have better structure for easy usage. You can look at this issue for more information #32

**Comment by meetDeveloper** [comment]
I have hosted API on AWS now, it won't have stability issues now.

This is the homepage. https://dictionaryapi.dev.

Way to query API has been changed a little:

Usage : The basic syntax of a URL request to the API is shown below:

https://api.dictionaryapi.dev/api/v1/entries/<--language_code-->/<--word-->

As an example, to get definition of English word hello, you can send request to

https://api.dictionaryapi.dev/api/v1/entries/en/hello
