### ISSUE TITLE
Support for multiple Definitions.

### ISSUE THREAD

**Issue by ScottEnock** [meetDeveloper/googleDictionaryAPI#5]
Depending on the word, Google will return multiple definitions for a word. For example, "steer" returns two separate definitions, the first being "guide or control the movement of (a vehicle, vessel, or aircraft)" and the second being "another term for Bullock.". 

At the moment the API only scrapes the first definition, It would be a nice addition if you could return all definitions. Thanks!

**Comment by meetDeveloper** [comment]
Thanks for suggestion, will do so by tomorrow.

**Comment by meetDeveloper** [comment]
Yeah sure, you can go on and implement it I will commit the changes, I was
kind of busy these few days in college and stuff. Thanks for the effort.

**Comment by meetDeveloper** [comment]
@martin-martin There?

**Comment by martin-martin** [comment]
Hei there! Haven't worked on it yet. Also busy myself and I'm mostly working with python, so I'd have to dig into the JS code you're using.

I'm still interested in your project and would love to collaborate in some ways - but maybe this is not the best feature for me to work on, especially if you have the time to do it yourself : )

**Comment by meetDeveloper** [comment]
@martin-martin Oh, It is all right. I will implement the feature soon. And suggest me some more features and I will be happy to implement them.

**Comment by meetDeveloper** [comment]
@ScottEnock I am really really sorry for so long delay, it has been so so long, I have implemented multiple definitions now, Thanks a lot for my first user of the API, I am sorry for the delay, life caught me. In case you have anything else just comment, I will this time make sure to add it right away. Thanks a lot for supporting the API since the start.

**Comment by meetDeveloper** [comment]
@martin-martin I added multiple definition feature. I am sorry for the delay, I was caught up in various things, I have implemented the feature if you find anything buggy, feel free to comment and I will correct it.

**Comment by ScottEnock** [comment]
@meetDeveloper Thanks for implementing this feature! No worries about the delay, I completely understand life gets in the way. I'm really happy using your API and proud to have been the first supporter. 

The only feature I can think that would be nice to have is when the Google ReCapture bot detection is triggered that the API responds with a status code, maybe the "424 Failed Dependency" code. Other than that I can't think of anything, keep up the great work.

**Comment by meetDeveloper** [comment]
@ScottEnock Thanks for your words. I also had that in mind, the Google ReCapture bot thing, I will implement it soon. May I ask how are you using this API?

**Comment by meetDeveloper** [comment]
Thanks @ScottEnock for suggesting the feature. Feature Implemented Successfully.

**Comment by ScottEnock** [comment]
@meetDeveloper It's my pleasure! I created a web app called Book Companion that lets you save words you come across when reading so that you can later revise them, here's a link to it: bookcompanionapp.com.

**Comment by ScottEnock** [comment]
Yep! On the backend, If there's no word stored in the database it'll do a search using the API to try and find it.

**Comment by meetDeveloper** [comment]
@ScottEnock Oh, That is great, when are you releasing the APP?
