### ISSUE TITLE
Support for English (UK)

### ISSUE THREAD

**Issue by sqlpedalianist** [meetDeveloper/googleDictionaryAPI#50]
It used to be possible to pass `en_GB` and get the definition from Oxford Dictionary of English instead of the American version.  I think that has stopped to work since last week.  I Would be happy if this option is officially supported since this is the default shown worldwide (except North America).

**Comment by meetDeveloper** [comment]
@sqlpedalianist Will fix this, this weekend. Meanwhile I have shifted API to AWS, it won't have stability issues now.

This is the homepage. https://dictionaryapi.dev.

Way to query API has been changed a little:

Usage : The basic syntax of a URL request to the API is shown below:

https://api.dictionaryapi.dev/api/v1/entries/<--language_code-->/<--word-->

As an example, to get definition of English word hello, you can send request to

https://api.dictionaryapi.dev/api/v1/entries/en/hello

**Comment by meetDeveloper** [comment]
Added support for English (UK). You can send request to `/api/v2/entries/en_GB/hello`. Can you check once, sorry for so late fix. @sqlpedalianist

**Comment by meetDeveloper** [comment]
Closing this ticket, sorry for so late reply. I will try to be more responsive from now. Really sorry.

**Comment by HubKing** [comment]
> Added support for English (UK). You can send request to `/api/v2/entries/en_GB/hello`. Can you check once, sorry for so late fix. @sqlpedalianist

If it has been fixed, please update the documentation page https://dictionaryapi.dev/ . It only shows "English (US)" at the try box, and "en" in the supported-language table at the bottom. I thought British English was not supported, and came here to make a feature request for that.

**Comment by meetDeveloper** [comment]
@HubKing Sorry for the delay, I have fixed this on website. Sorry for the inconvenience. Thank you for using my API.
