### ISSUE TITLE
Finding this API has a high latency

### ISSUE THREAD

**Issue by tejeshreddy** [meetDeveloper/googleDictionaryAPI#52]
Taking a lot of time to return a response

**Comment by meetDeveloper** [comment]
@tejeshreddy Will move to different plan soon.

**Comment by meetDeveloper** [comment]
I have hosted API on AWS now, it won't have stability issues now.

This is the homepage. https://dictionaryapi.dev.

Way to query API has been changed a little:

Usage : The basic syntax of a URL request to the API is shown below:

https://api.dictionaryapi.dev/api/v1/entries/<--language_code-->/<--word-->

As an example, to get definition of English word hello, you can send request to

https://api.dictionaryapi.dev/api/v1/entries/en/hello

**Comment by tejeshreddy** [comment]
Thanks @meetDeveloper, that was really helpful.

**Comment by meetDeveloper** [comment]
Shall I Close the issue?

**Comment by tejeshreddy** [comment]
Yes
