### ISSUE TITLE
https://mydictionaryapi.appspot.com/ not working anymore

### ISSUE THREAD

**Issue by sks316** [meetDeveloper/googleDictionaryAPI#54]
I run a Discord bot that uses this API for dictionary definitions. It began throwing errors about "Attempt to decode JSON with unexpected mimetype", and I looked on the API which is no longer returning any definitions at all. The other URL seems to still work fine, however.

**Comment by meetDeveloper** [comment]
@sks316 I will check and fix it today.

**Comment by meetDeveloper** [comment]
@sks316 
I have hosted API on AWS now, it won't have stability issues now.

This is the homepage. https://dictionaryapi.dev.

Way to query API has been changed a little:

Usage : The basic syntax of a URL request to the API is shown below:

https://api.dictionaryapi.dev/api/v1/entries/<--language_code-->/<--word-->

As an example, to get definition of English word hello, you can send request to

https://api.dictionaryapi.dev/api/v1/entries/en/hello

**Comment by meetDeveloper** [comment]
This is lot faster and will be reliable endpoint, kindly shift to this.

**Comment by ojoven** [comment]
You're great, thanks for all the effort you're putting on this tool!

**Comment by sunnyjain** [comment]
Yes. Pretty Fast! Thanks. Appreciate it.
