### ISSUE TITLE
Thanks a lot for great help. But it does not support languages other than English.Kindly fix this issue.

### ISSUE THREAD

**Issue by SamraMehboob** [meetDeveloper/googleDictionaryAPI#55]

**Comment by meetDeveloper** [comment]
@SamraMehboob It does support many, you can send the query as `?define=<word>&lang=<langCode>`. You can find the list of supported languages [here](https://googledictionaryapi.eu-gb.mybluemix.net/languageCode.txt.).

Ex: https://googledictionaryapi.eu-gb.mybluemix.net/?define=house&lang=en

**Comment by meetDeveloper** [comment]
I have hosted API on AWS now, it won't have stability issues now.

This is the homepage. https://dictionaryapi.dev.

Way to query API has been changed a little:

Usage : The basic syntax of a URL request to the API is shown below:

https://api.dictionaryapi.dev/api/v1/entries/<--language_code-->/<--word-->

As an example, to get definition of English word hello, you can send request to

https://api.dictionaryapi.dev/api/v1/entries/en/hello
