### ISSUE TITLE
Hosted API on AWS

### ISSUE THREAD

**Issue by meetDeveloper** [meetDeveloper/googleDictionaryAPI#56]
I have hosted API on AWS, Kindly shift to API hosted on https://dictionaryapi.dev.

Way to query API has been changed a little:

Usage : The basic syntax of a URL request to the API is shown below:

https://api.dictionaryapi.dev/api/v1/entries/<--language_code-->/<--word-->

As an example, to get definition of English word hello, you can send request to

https://api.dictionaryapi.dev/api/v1/entries/en/hello

**Comment by victorsmseo** [comment]
The phonetic seems to give weird characters

**Comment by meetDeveloper** [comment]
@victorsmseo Can you give example, for which word did you got weird characters?

**Comment by victorsmseo** [comment]
https://api.dictionaryapi.dev/api/v1/entries/en/hello
It gives "phonetic": "/hÉ™ËˆlÅ/"

**Comment by meetDeveloper** [comment]
For me it is coming like this, can you hit API with curl and then tell me response.

<img width="657" alt="Screenshot 2020-02-21 at 11 23 31 PM" src="https://user-images.githubusercontent.com/32453612/75058578-4342c900-5501-11ea-9de3-5965f50ae92e.png">

**Comment by victorsmseo** [comment]
I found out that the characters were crashing in Safari. Checked them out in Chrome and works like a charm. Thanks!

**Comment by davwheat** [comment]
I didn't realise there was a new endpoint. You might want to add a comment to the old API endpoint warning of future deprecation.

**Comment by nealchawn** [comment]
Thanks for your comment I had no idea either !

**Comment by meetDeveloper** [comment]
Have included version 2 also, 

https://api.dictionaryapi.dev/api/v2/entries/<--language_code-->/<--word-->

This changes the way API gives output.

**Comment by meetDeveloper** [comment]
Thank you all for using my API and helping it reach here.

**Comment by meetDeveloper** [comment]
@davwheat @nealchawn  There is V2 endpoint also now.
