### ISSUE TITLE
Extra whitespace at beginning of word example

### ISSUE THREAD

**Issue by ElectrifyPro** [meetDeveloper/googleDictionaryAPI#58]
I encountered a few words that have extra whitespace at the beginning of their examples, for example, [hindsight](https://api.dictionaryapi.dev/api/v3/entries/en/hindsight)

I believe this wouldn't be too difficult to fix?

**Comment by meetDeveloper** [comment]
@ElectrifyPro I will fix it as soon as possible, thanks for finding that out.

**Comment by meetDeveloper** [comment]
I think the problem automatically went away, could not see in the word `hindsight`. Can you confirm @ElectrifyPro .
cc @manishsaraan I think we won't be needing the fix if this problem does not surface up.

**Comment by ElectrifyPro** [comment]
Yes, it seems to have been fixed

**Comment by meetDeveloper** [comment]
@manishsaraan Do you know of any other examples where this problem can be manifested?
