### ISSUE TITLE
Unable to fetch word pronunciation

### ISSUE THREAD

**Issue by manishsaraan** [meetDeveloper/googleDictionaryAPI#60]
Api is not returning word pronunciation for English words. I found the bug fix. Will raise a pr.

**Comment by ScottON** [comment]
Any update on this? When I used the API in the past  it would return the phonetic pronunciation. Hope this gets fixed asap. Thanks!

**Comment by manishsaraan** [comment]
@meetDeveloper did you review pr for this issue ?

**Comment by GE0NE** [comment]
Any update on this?

**Comment by meetDeveloper** [comment]
@GE0NE @ScottON @manishsaraan Sorry for so late response, life got me. I have merged @manishsaraan PR and also made some other changes, I have deployed the fix and you guys can test and tell me. 

Sorry once again for keeping this open for so long, I will try to be more responsive next time. Thank you for using my Dictionary API.

**Comment by meetDeveloper** [comment]
Also I am using Cloudfront so meaning are cached, I need to bust the cache so that you guys see the phonetics.

**Comment by meetDeveloper** [comment]
I have invalidated the cache, now you will see the phonetics. Again really sorry for delaying this this much.

**Comment by manishsaraan** [comment]
Thanks for merging the pr @meetDeveloper . Also no issue regarding the response. we all are in same boat in these testing times :+1:

**Comment by meetDeveloper** [comment]
@GE0NE @ScottON Have you guys seen the changes?
