### ISSUE TITLE
Synonyms for other languages (and antonym if its possible)

### ISSUE THREAD

**Issue by JRamos29** [meetDeveloper/googleDictionaryAPI#62]
Hi,
It's possible to get the synonyms (and antonyms) for other languages? I tested all languages but just english show the synonyms.

**Comment by meetDeveloper** [comment]
There is some problem with other languages will fix that this weekend.

**Comment by meetDeveloper** [comment]
Are you using API v1 or v2?

**Comment by JRamos29** [comment]
I'm using API v2. 
After the fix i will can get the synonyms for other languages?
Tnks for the answer.

**Comment by meetDeveloper** [comment]
@JRamos29  Yes.

**Comment by JRamos29** [comment]
Great! Hope you can implement that soon. 
Tnks in advance.

**Comment by meetDeveloper** [comment]
@JRamos29  Can you give me some word for which synonyms are coming in google but not in api?

**Comment by JRamos29** [comment]
When you say 'google' what you mean? A general search in google or some specific tool like translator? 
By the way I haven't searched the words with google, i just tested the api with Postman, and the other languages doesn't have synonyms, just English. 
The API only gets synonyms if exists in google? What is the URL for search?

The examples bellow doesn't have synonyms, the array comes empty: 
French: mot - https://api.dictionaryapi.dev/api/v2/entries/fr/mot
Portuguese-BR: palavra: https://api.dictionaryapi.dev/api/v2/entries/pt-BR/palavra

But this has the synonyms:
English: word - https://api.dictionaryapi.dev/api/v2/entries/en/word

**Comment by meetDeveloper** [comment]
I made many changes to the API. Now it will return antonym and synonym for the words which have that on google. So I am taking data from google and others and if they have synonym I show synonyms.

**Comment by meetDeveloper** [comment]
<img width="600" alt="Screenshot 2020-06-16 at 8 06 55 PM" src="https://user-images.githubusercontent.com/32453612/84788831-35173c00-b00d-11ea-9d4a-04175433866c.png">
The area under square that is one that I pick up. So if that is there, I will pick it up and show.

**Comment by JRamos29** [comment]
Nice. But it's for English. I think that won't have for other languages, or not for all languages. But it's ok, i'll try another way to get the synonyms for other languages if not have in the API. 
Tnks.

**Comment by meetDeveloper** [comment]
For whatever word (and it shows for words not belonging to english also) google shows synonyms I will parse them and show it. I will try to find more sources for synonyms.

**Comment by JRamos29** [comment]
When I search a word in google it brings the definitions in English only. Did you already published the changes?

**Comment by meetDeveloper** [comment]
Search for word dictionary in google and modify url to add hl=lang_code as
query param.
Then you will see the dictionary in that language. To get list of anguage
code you can see the list on my website.

Like Spanish language code is es and so on.

**Comment by meetDeveloper** [comment]
Synonyms are available for both English and other languages, and antonyms are available for languages other than English. Will make sure english also has antonyms soon. Closing this issue as this was for languages other than english. @JRamos29
