### ISSUE TITLE
Call to api is not returning results frequently.

### ISSUE THREAD

**Issue by ssabbarw** [meetDeveloper/googleDictionaryAPI#63]
i started using this api 2 days back and it was working great. I have written all my logic/data structures(for my flutter app) around the result returned by this api.
However since morning today, many calls are failing. Even for very simple words. Both in browser and via code.

To **summerize** the problem i am facing: Calls for (simple) words are failing many times and giving results some other times. Out of 10 maybe 2/3 are giving results rest are giving me the result i have shown in the screenshot below.
All these calls were working fine for same words till yesterday.

1. Is it possible that this api or google is doing some throttling because of frequent calls?
2. Is there any quota for number of calls one can make per day/month?
<img width="961" alt="Screenshot 2020-06-12 at 8 04 12 PM" src="https://user-images.githubusercontent.com/41985865/84514340-80b5a700-ace8-11ea-86a0-926a9df97712.png">

**Comment by meetDeveloper** [comment]
@ssabbarw I will take this on urgent priority and fix it, could you shift to `v2` version, I need to update that on website the documentation though I have update that as readme in this document.

**Comment by ssabbarw** [comment]
Hi
I am using v2 in my app. Calls using both v2 and v1 are failing. When they started failing with v2 i tried v1. It’s by chance that i have given you a screen shot of v1 here.

**Summary**: both v1 and v2 calls were failing. I pasted the v1 screenshot only.
**Question**: is it possible that the api or the google is doing some kind of throttling? Denying to serve requests?

Thanks

**Comment by meetDeveloper** [comment]
API is not doing throttling, if that was the case you would have received rate limit error. I will soon start to implement caching mechanism so that I cache all the words and meaning seen until now and this way won't be depending on the provider.

**Comment by ssabbarw** [comment]
Thanks for prompt reply.
But do u think caching will help? Because i am getting 404 for even new words. Maybe google is throttling because of too many calls? 
I am a newbie. Apologies if i am asking navie questions or not able to explain properly. 
If u want help reprodouce this we can connect on telegram. I am t.me/kickel_dev on telegram.

**Comment by ssabbarw** [comment]
so the api now returns response code 429: too many requests,

 "title": "API Rate Limit Exceeded",
    "message": "Sorry pal, you were just rate limited by the **upstream server.**",
    "resolution": "You can try the search again at later time or head to the web instead."

Questions: 
1. what is the rate limit here, like how many calls can we make per day/hour?

Thanks for acting quickly though.

**Comment by meetDeveloper** [comment]
@ssabbarw Will add caching so that API does not depend on upstream server too much. I have this in roadmap next.

**Comment by meetDeveloper** [comment]
@ssabbarw Also adding ratelimit based on IP, this way people who are using script to hit server at huge rate to download all meanings will be reduced.

**Comment by ssabbarw** [comment]
Should work fine with Caching.. 
shall i close this issue now or will you close this yourself after you implement both?

**Comment by meetDeveloper** [comment]
@ssabbarw  I think you can close it, I will create another feature issue to fix them.

**Comment by ssabbarw** [comment]
Thanks for your prompt replies. I will close it now.
