### ISSUE TITLE
French example isn't working

### ISSUE THREAD

**Issue by jackkenlay** [meetDeveloper/googleDictionaryAPI#64]
https://api.dictionaryapi.dev/api/v2/entries/fr/bonjour returns no entry, has something changed? It works on v1.

**Comment by meetDeveloper** [comment]
Looking into it..

**Comment by garciadiazjaime** [comment]
@meetDeveloper same issue happens on other languages as well,
maybe google disabled their endpoint?

[https://www.google.com/async/dictw](https://github.com/meetDeveloper/googleDictionaryAPI/blob/master/modules/dictionary.js#L156)

**Comment by meetDeveloper** [comment]
Can you try it now @jackkenlay @garciadiazjaime

**Comment by garciadiazjaime** [comment]
@meetDeveloper working now! 👍 

what was it?, if you don't mind sharing :)

Thanks!

**Comment by meetDeveloper** [comment]
URL was changed, I fixed that. 😄

**Comment by meetDeveloper** [comment]
@jackkenlay Can you close the issue if this is working for you?

**Comment by JereMiO** [comment]
it doesn't work
