### ISSUE TITLE
Error in Google Async Link

### ISSUE THREAD

**Issue by KavinAgrawal** [meetDeveloper/googleDictionaryAPI#65]
Hi Team,
I went through your github repository and used it to develop some similar things in my project. It was working very fine. However, the link "https://www.google.com/async/dictw?hl=${language}&async=term:${word},corpus:${language},hhdr:false,hwdgt:true,wfp:true,xpnd:true,ttl:,tsl:${language},_id:dictionary-modules,_pms:s,_jsfs:Ffpdje,_fmt:pc"  for getting meanings from google is giving Error 404 for my app from past two days. However, your code(api call) is still able to get these dictionary meanings from google perfectly. Can you tell if any different way you have handled your get requests or have you changed your url link. Also how do you retrieve these links for google async call?

**Comment by meetDeveloper** [comment]
@KavinAgrawal  I have all the meaning already fetched and I am using that instead of URL. What for do you need url for?

Sorry for late reply, life got me .

**Comment by KavinAgrawal** [comment]
Actually your api results for English words do not contain any phonetic. So I decided to make my own dictionary using the  google link you used in the dictionary.js file. But that link is now expired and giving out Error 404

**Comment by meetDeveloper** [comment]
@KavinAgrawal I have now added the phonetics and pronunciations. I added this yesterday only, can you once look and tell if that is what you needed.

**Comment by meetDeveloper** [comment]
@KavinAgrawal closing this ticket, you can open new ticket if you encounter any problems with the phonetic and permission API is returning. I have currently significantly stabilised the phonetics and pronunciations.
