### ISSUE TITLE
Android integration

### ISSUE THREAD

**Issue by Inrovero** [meetDeveloper/googleDictionaryAPI#67]
Hi there! I'm having some troubles to integrate this api in my android app..
I need to create an object to read and deserialize the JSON response of this api, but i'm not shure how to adapt it..
Can u help me?

And another request is.. There is a way to get the JSON Response without spaces or endlines?

Regards and congrats for this fantastic api,
Inrovero

**Comment by meetDeveloper** [comment]
@Inrovero You need to parse JSON and convert into object. Lines and spaces won't matter then.

**Comment by meetDeveloper** [comment]
@Inrovero You can take a look at this, https://stackoverflow.com/questions/14812560/how-to-parse-the-json-response-in-android

**Comment by Inrovero** [comment]
@meetDeveloper Thanks for your reply! I'm going to attack this tomorrow, i've already worked with json objects and json arrays in java, but i've thinked that this time it might be different..
Anyway, do u have some sort of document with all possible responses from the dictionary's json? e.x: don't have meaning, have a lot of meanings, get an error, the word doesn't exists, etc

**Comment by meetDeveloper** [comment]
@Inrovero I will add those in the documentation. You can look at these 4 to find all the types of object API can return.

https://api.dictionaryapi.dev/api/v2/entries/en/hello (Top level Array having only 1 object inside it)
https://api.dictionaryapi.dev/api/v2/entries/en/set (Top level Array having multiple objects inside it)
https://api.dictionaryapi.dev/api/v2/entries/en/absad (404)
https://api.dictionaryapi.dev/api/v2/entries/es/hola (languages other than english also has antonym section)

**Comment by meetDeveloper** [comment]
@Sharkaboi I will soon make english and other languages format same, work is going on in this direction, it is taking some time, I can add empty field but that kind of is an hack that is why I have not added till now.
