### ISSUE TITLE
Google's API/URL is no longer working, returning 404

### ISSUE THREAD

**Issue by bass3l** [meetDeveloper/googleDictionaryAPI#68]
Hi,

Google's API/URL is no longer working, returning 404. I've checked the other issues, and I think it's reported.

On dictionaryapi.dev it's working, so did you figure out the new URL? or are you using a cached dictionary? 

I'm using some of the code in my own project to fetch words and **verbs**, hence I'm not able to use dictionaryapi.dev in its fullest.

Thank you for your work.

**Comment by meetDeveloper** [comment]
I have cached dictionary and also other sources to fetch definitions. I am closing this ticket, we can chat on closed ticket, as the title suggests that the API which I provide is not working.
