### ISSUE TITLE
Other languages do not work

### ISSUE THREAD

**Issue by zxl777** [meetDeveloper/googleDictionaryAPI#69]
https://api.dictionaryapi.dev/api/v2/entries/ja/hello
https://api.dictionaryapi.dev/api/v2/entries/zh-CN/hello

{
"title": "No Definitions Found",
"message": "Sorry pal, we couldn't find definitions for the word you were looking for.",
"resolution": "You can try the search again at later time or head to the web instead."
}

**Comment by iigmir** [comment]
Here are my results:

Successful cases:

- https://api.dictionaryapi.dev/api/v2/entries/ja/こんにちは
- https://api.dictionaryapi.dev/api/v2/entries/ja/あなた
- https://api.dictionaryapi.dev/api/v2/entries/zh-CN/你

Failed cases:

- https://api.dictionaryapi.dev/api/v2/entries/ja/hello
- https://api.dictionaryapi.dev/api/v2/entries/ja/ハロー
- https://api.dictionaryapi.dev/api/v2/entries/zh-CN/hello
- https://api.dictionaryapi.dev/api/v2/entries/zh-CN/你好

I guess the dictionary API only provides words used in the specified language(Imagine that you are finding the word "hello" in a Japanese dictionary, and finding the word "你" in a Chinese dictionary). Also, some languages' words are very limited.

**Comment by zxl777** [comment]
Thanks, Maybe it is just English to English dictionary.

**Comment by rpungin** [comment]
I tried this with Russian: https://api.dictionaryapi.dev/api/v2/entries/ru/стул which is looking up the word "chair"
and got that same error. Looks like Russian does not work.

**Comment by meetDeveloper** [comment]
@rpungin I have fixed this issue.

@zxl777 Just like @iigmir said The API only checks the dictionary of chosen language, so like if the language is Japanese you won't find word `hello` in that, you have to search for Japanese translation of word `hello`.

@zxl777  I don't think the other feature that you are looking for will be supported in near future.
