### ISSUE TITLE
404 Not Found

### ISSUE THREAD

**Issue by sridvenk** [meetDeveloper/googleDictionaryAPI#8]
Hi, service was working fine yesterday, but when I try to today I get a 404 Not Found with the following message:
Not Found
We're sorry, we couldn't find what you were looking for.
You can try a search or start over on the home page.

The starting webpage loads okay, but any query returns the above error.

**Comment by meetDeveloper** [comment]
Maybe google has changed the classes name, on which it works, I will correct it soon. Thanks for informing.

**Comment by meetDeveloper** [comment]
@sridvenk  is it working now??
